# Generated by Django 5.0.7 on 2024-07-29 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio', models.PositiveIntegerField()),
                ('actores', models.ManyToManyField(related_name='peliculas', to='AppAnni.actor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAnni.genero')),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='mascota',
        ),
        migrations.DeleteModel(
            name='ParticipanteCita',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
